/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jc_jcsports_utils_videotrim_NDK */

#ifndef _Included_com_jc_jcsports_utils_videotrim_NDK
#define _Included_com_jc_jcsports_utils_videotrim_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jc_jcsports_utils_videotrim_NDK
 * Method:    ffmpeg
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_jc_jcsports_utils_videotrim_NDK_ffmpeg
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     com_jc_jcsports_utils_videotrim_NDK
 * Method:    videoFileToPpm
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jc_jcsports_utils_videotrim_NDK_videoFileToPpm
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_jc_jcsports_utils_videotrim_NDK
 * Method:    mp4Andmp3Remux
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_jc_jcsports_utils_videotrim_NDK_mp4Andmp3Remux
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     com_jc_jcsports_utils_videotrim_NDK
 * Method:    mp3ControlDuration
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_jc_jcsports_utils_videotrim_NDK_mp3ControlDuration
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     com_jc_jcsports_utils_videotrim_NDK
 * Method:    test
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jc_jcsports_utils_videotrim_NDK_test
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
